default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  # timeout: 5000

development:
  <<: *default
  database: readfavor_development

test:
  <<: *default
  database: readfavor_test

production:
  <<: *default
  database: readmatters_production
