default: &default
  adapter: postgres
  encoding: unicode
  pool: 5
  # timeout: 5000

development:
  <<: *default
  database: readfavor_development

test:
  <<: *default
  database: readfavor_test

production:
  <<: *default
  database: readfavor_production
